= Compte rendu COO Groupe 14

Dans ce document, nous allons vous montrer :

* Des maquettes d’écran
* Un diagramme des cas d’utilisation
* Un diagramme de séquence système pour la création d'un serveur
* Un diagramme des classe probables de l’application

Maquettes écran
^^^^^^^^^^^^^^^

Pour commencer nous allons vous parler des maquettes écran :
Au total, nous en avons réalisé 8. Chacune d'elles présente une interface de l'application.

La première maquette montre l'interface de gestion d'un serveur (si l'on possède les droits pour).

La deuxième maquette, toujours dans la gestion d'un serveur, servira à gérer les logs du serveur.

La troisième maquette s'intéresse cette fois à la section modération du serveur.

La quatrième maquette, la dernière en lien avec la gesion d'un serveur, montre la gestion des rôles et des permissions attribuables.

La cinquième se concentrera sur la liste d'amis de l'utilisateur.

La sixième montre l'interface d'un serveur lorsqu'on y accède sans modifier ses paramètres.

L'avant-dernière montre l'interface des conversations privées avec les autres utilisateurs.

Enfin, la dernière maquette affiche les paramètres du compte de l'utilisateur qui peuvent être modifiés.

Diagramme des cas d'utilisations
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dans cette partie, nous avons créer un diagramme qui va référencer toute les utilistaions possibles pour un utilisateur :

* créer un serveur
* créer_serveur
* prendre un abonnement
* envoyer des messages
* ajouter des amis
* appeler
* se connecter

On peut retrouver toute ces fonctionnailtés sur le maquetage.

Ainsi nous avons pu créer ce diagramme qui liste toute les possibilités. 

On remarque aussi la présence du serveur qui va récupérer toute les actions éffectuer par l'utilisateur.

 [plantuml, diagram-classes, png]
 ....
left to right direction

:Utilisateur: #aliceblue;line:blue;text:blue
:Serveur:


usecase se_connecter as "Se connecter"
usecase inscription as "S'inscrire"
usecase formulaire as "Remplir formulaire"

usecase appeler as "Appeler"
usecase partecran as "Partager son écran"
usecase camera as "Caméra"
usecase coupmic as "Couper micro"
usecase coupcasque as "Couper casque"

usecase ajouter_amis

usecase envoyer_message as "Envoyer un message"
usecase envpho as "Envoyer photo"
usecase envdoc as "Envoyer document"
usecase envemoji as "Envoyer émojie"
usecase envgif as "Envoyer gif"

usecase prendre_abonnement as "Prendre un abonnement"
usecase offrir as "Offrir abonnement"
usecase payer as "Payer abonnement"

usecase créer_serveur as "Créer un serveur"
usecase formulserv as "Remplir formulaire serveur"
usecase amisserv as "Inviter amis"
usecase créer_salon as "Créer un salon"
usecase créer_salon_vocale as "Créer un salon vocale"
usecase créer_salon_texte as "Créer un salon textuel"

Utilisateur --> se_connecter
inscription --> se_connecter
formulaire --> inscription

Utilisateur --> appeler
appeler --> coupmic
appeler --> coupcasque
appeler --> partecran
appeler --> camera

Utilisateur --> ajouter_amis

Utilisateur --> envoyer_message
envoyer_message --> envdoc
envoyer_message --> envemoji
envoyer_message --> envgif
envoyer_message --> envpho

Utilisateur --> prendre_abonnement
prendre_abonnement --> offrir
prendre_abonnement --> payer

Utilisateur --> créer_serveur
créer_serveur --> amisserv
créer_serveur --> formulserv
créer_serveur --> créer_salon
créer_salon --> créer_salon_vocale
créer_salon --> créer_salon_texte

Serveur <-- créer_serveur
Serveur <-- prendre_abonnement
Serveur <-- envoyer_message
Serveur <-- ajouter_amis
Serveur <-- appeler
Serveur <-- se_connecter
....



diagramme de séquence système
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^







diagramme des classe probables de l’application
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

