= Compte rendu COO Groupe 14

Dans ce document, nous allons vous montrer :

* Des maquettes d’écran
* Un diagramme des cas d’utilisation
* Un diagramme de séquence système pour la création d'un serveur
* Un diagramme des classe probables de l’application

Maquettes écran
^^^^^^^^^^^^^^^

Pour commencer nous allons vous parler des maquettes écran :
Au total, nous en avons réalisé 8. Chacune d'elles présente une interface de l'application.

La première maquette montre l'interface de gestion d'un serveur (si l'on possède les droits pour).
image::https://discord.com/channels/@me/753676281417171114/845342660231299092[alt="1-interface-gestion-d-un-serveur.png",width=1290,height=699]

La deuxième maquette, toujours dans la gestion d'un serveur, servira à gérer les logs du serveur.

La troisième maquette s'intéresse cette fois à la section modération du serveur.

La quatrième maquette, la dernière en lien avec la gesion d'un serveur, montre la gestion des rôles et des permissions attribuables.

La cinquième se concentrera sur la liste d'amis de l'utilisateur.

La sixième montre l'interface d'un serveur lorsqu'on y accède sans modifier ses paramètres.

L'avant-dernière montre l'interface des conversations privées avec les autres utilisateurs.

Enfin, la dernière maquette affiche les paramètres du compte de l'utilisateur qui peuvent être modifiés.

Diagramme des cas d'utilisations
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dans cette partie, nous avons créer un diagramme qui va référencer toute les utilistaions possibles pour un utilisateur :

* créer un serveur : on peut retrouver cela sur le sixième maquetage (le bouton plus en bas de la liste des serveurs).
* prendre un abonnement on peut retrouver cela sur le huitième maquetage ( les paramètres discord nitro).
* envoyer des messages : on peut retrouver cela sur le sixième maquetage.
* ajouter des amis : on peut retrouver cela sur le septième maquetage.
* appeler : on peut retrouver cela sur le sixième maquetage.
* se connecter : on peut retrouver cela sur le neuvième maquetage.

On peut retrouver toute ces fonctionnailtés sur le maquetage.

Ainsi nous avons pu créer ce diagramme qui liste toute les possibilités. 

On remarque aussi la présence du serveur qui va récupérer toute les actions effectuer par l'utilisateur.

image:https://plantuml-server.kkeisuke.dev/png/XLL9RXin4Bpp5SJau9C-80U1Wo27d6p4o5cWgHwP1ZTp4U8dwHtwc9jBDEGioArPLMHpcbMO1n-O2r598c4CD1ZgnEarqADmm8Cmcf3zdo2ay2n0T7lwXKd1uKL6k9T2mpvN0Vw6N97zCxXp4X92eWVEF50F1swqnlF0KURfy0pq1WmtcT2UEs5JqwAwAuY3IJCQfw9aY6N9Rr1M2jV0mzIMMGkoTlnUwkaWYryDtB7IwWbNx8HQZxslbuHFKiuKE9PrFvYwNXnhE1Ej4hoGMECHk7IcLs3n7g4L5QIzx9k9E8q3Ky9FAEYp-K1KWVTultp2puBHg6c5XrPlNqqdmtKmdU9eUAV0TLIWGoS2PTv49xjU4jGtEucnq-2w-IRhG1yT7DXBUkpKeWoxmEa39cOwremZldbMFjPoHMNPHttQfr8rccdsxdh1wVbYoJB_3ANU5PrxAy4RtbfkIQzrs_1BdqLsE8B3uWvCLbitDqZOkl9mDfn9MDj02xMnBoLnVLjY8aWSJvDdkjjzw_99sXGko6OMYMkqorDh_CY_62QincM1bJXqy2sWlJXdSQLP5vyvEuiHcSUgQZ08MrIEmnQ9hj-YC7tBwonpGLQYafGb2rjipi3o-DxrP1Q2FArgspLkIi4QstgDTDQUizN1_n5bkn9IVnhqwsutltvBhGokfUVFt7ATGJgYshJ5Eiy_O4_yFtu2.png[width=50%,height=50%]



diagramme de séquence système
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

image:https://plantuml-server.kkeisuke.dev/png/XO_13SCm24Nlde85ia0EKJQfK4mh96n76B9JvkXYfMgZfkgXtE3h_V-Pkw6Q5qatRRx2elSTZLkzTDADN1F4kB5mHuiTXWdU4eoGgM3DzC7WZE5Yl0NrTJpW8OpElYCebLLOGGYkJOiBij8Vvb2U1UWLaEadDyrKSppv0000.png[width=100%,height=100%]





diagramme des classe probables de l’application
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

