@startuml ClassesProbables
'--------------------------------
' Parametres pour le dessin
'--------------------------------
hide circle
hide empty members
hide empty methods
'--------------------------------


'--------------------------------
'Partie serveur 
'--------------------------------
class Fiche 
{
  nomP
  prenomP
  imageP
  initialesP
  surnomP
  descriptionP
  listeMatieres
  fiche

}




class Module
{
    nomM
}




class Compte
{
    login 
    motDePasse
    

    seConnecter()
}

class CompteProfesseur
{
   fiche

   modifierFiche()
}

class CompteSecrétariat
{
   créerProfesseur()
   definirModuleEnseignant()
}




CompteProfesseur --|> Compte
CompteSecrétariat --|> Compte



Fiche "1..*"--"1..*" Module : Enseigne
CompteProfesseur "1" -- "1" Fiche : Appartient


(Fiche, Module) . ListeModules


'---------------------------------
 

@enduml