@startuml ClassesProbables
'--------------------------------
' Parametres pour le dessin
'--------------------------------
hide circle
hide empty members
hide empty methods
'--------------------------------


'-------------------------
'Partie serveur 
'---------------------
class Serveur
{
   idServeur
   nomServeur


   

}

class Role
{
    idRole
    nomRole
    permissions
    couleur


}

class Emoji
{
    idEmoji
    nomEmoji
    imageEmoji
    


}

class Salon
{
    idSalon
    nomSalon

}

'--------------------------



'--------------------------
'Contact 
'------------------------
<> diamondContact

class ListeContact
{
    listeContact
    nombreContact
}

ListeContact . diamondContact
diamondContact  -- "1" Compte
diamondContact  -- "1" Compte
'------------------------------



'------------------------
'Classes diverses
'-----------------------

class Compte
{
    idCompte
    pseudo
    photoProfil
    messageStatut
    statutConnexion
}

class Groupe
{
idGroupe
nomGroupe
imageGroupe

}



'----------------------------




'----------------------------
'Les lisisons
'------------------------------
Serveur "1" -- "*"  Role 
Serveur "1" -- "*..50"  Emoji 
Serveur "1" -- "*..50"  Salon 
Serveur "*..100" -- "1..*"  Compte : est membre
Serveur "1" -- "*"  Compte : est propriétaire
Groupe "*" -- "1..10" Compte : est membre
Groupe "*" -- "1" Compte : est propriétaire





'---------------------------------
 

@enduml